name: akbulut_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # CORE & FIREBASE
  cupertino_icons: ^1.0.6 
  flutter_lints: ^5.0.0
  # STATE MANAGEMENT & UTILITIES
  get: ^4.7.2
  intl: ^0.19.0
  collection: ^1.18.0
  http: ^1.1.0 
  file_saver: ^0.2.12
  excel: ^4.0.6
  # UI COMPONENTS & ANIMATIONS
  omni_datetime_picker: ^2.3.1
  flutter_iconly: ^1.0.2
  hugeicons: ^0.0.11
  fl_chart: ^0.68.0         
  kartal: ^4.1.0
  lottie: ^3.0.0
  get_storage: ^2.1.1 
  flutter_svg: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/image/
    - assets/translations/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
  uses-material-design: true
  generate: true
